### ISSUE TITLE
Root of https://paraspell.github.io points to nowhere 

### ISSUE THREAD

**Issue by vikiival** [paraspell/docs#13]
### Context 

When someone goes to https://paraspell.github.io they see `404` 
it would be nice to automatically redirect them to `https://paraspell.github.io/docs`

**Comment by dudo50** [comment]
Resolved by quite obscure way - creating new repository: https://github.com/paraspell/paraspell.github.io

Apparently, there is no other way around this.

Thanks for the suggestion!
